package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserPass;

public interface UserPassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Aug 28 12:48:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Aug 28 12:48:02 CST 2019
     */
    int insert(UserPass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Aug 28 12:48:02 CST 2019
     */
    int insertSelective(UserPass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Aug 28 12:48:02 CST 2019
     */
    UserPass selectByPrimaryKey(Integer id);

    UserPass selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Aug 28 12:48:02 CST 2019
     */
    int updateByPrimaryKeySelective(UserPass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Aug 28 12:48:02 CST 2019
     */
    int updateByPrimaryKey(UserPass record);
}